### ISSUE TITLE
Query lookup doesn’t appear to be bundled

### ISSUE THREAD

**Issue by smartmike** [smhg/express-locale#7]
Setting up the middleware with config with `express-locale` version `^1.0.0`

```
app.use(locale({
  priority: ['query', 'cookie', 'accept-language', 'hostname', 'map', 'default'],
  ...
}))
```

I get the error `Error: Locale lookup source method "query" not defined`

When inspecting the bundled code, it does indeed appear to be missing...

`lib/index.js`:
```
var LOOKUPS = {
  'cookie': _cookie2.default,
  'hostname': _hostname2.default,
  'accept-language': _acceptLanguage2.default,
  'default': _default2.default
};
```

Any ideas? Thanks!

**Comment by smhg** [comment]
It sounds like express-locale is incorrectly cached on your machine.

When I do `npm i express-locale` in an empty folder, lib/index.js is the proper version.
FWIW: I use npm version 3.10.9 (on node 4.6.2).

Can you do `npm cache clean express-locale` and reinstall? Does that fix it?

If so, it might still be related to the registry itself, as I had to e-mail them to update the page on npmjs.com. It kept showing the old version.

**Comment by smartmike** [comment]
I still get the same result, even when I create an empty project and install. This is node version `6.9.1`, and npm version `3.10.8`.

I created a fork and pushed the built files up and referenced this in my local project, which works, so I'm not sure why I'm not getting the correct build from npm!

**Comment by smhg** [comment]
I've contacted npm about this because I have no idea what is happening.

**Comment by smhg** [comment]
Below the feedback of npm. Could you please contact them directly and let me know what the outcome is?
It is an awkward issue that I'd like to get resolved.

Thanks!

> Stephanie Snopek (npm)
> Nov 28, 17:09 PST
> 
> Hello Sam,
> 
> Thanks for checking in. We'll need a bit more information to figure this out. Are they getting express-locale@0.1.2 when asking for express-locale@latest?
> 
> For clearer communication, I'd recommend CC'ing them to this thread, or asking them to get in touch with us directly.
> 
> Thanks so much, 
> Stephanie

**Comment by smartmike** [comment]
Hey, I can do that, can you just try these steps and see if you get the same results as me, that would be useful info to pass on.

```
mkdir test-express-locale && cd test-express-locale
npm init
... enter all the way through
npm i express-locale --save
cd node_modules/express-locale
cat package.json
[... expect "version": "1.0.0"]
cd lib/lookup
ls
[... expect accept-language.js cookie.js          default.js         domain.js          hostname.js]
```

Thanks!

**Comment by smhg** [comment]
Ok, I found the issue.
Your steps led to the same result. I don't know why it didn't happen before.
I was using the `prepublishOnly` script, which is only available in npm 4. Apparently I used npm 3 to publish 1.0.0 (so no `prepublishOnly` and no build).
Fixed that and published 1.0.1.
Thank you for your efforts!

**Comment by smartmike** [comment]
I'm really not sure why, but I still get the same results on 1.0.1 – Sorry for the headache!

**Comment by smhg** [comment]
If I perform your steps above the result is what it should be (including `query.js`).
Does `npm cache clean express-locale` help this time?

**Comment by smartmike** [comment]
Okay, yes, that's done it, sorry – I thought I had tried this. Thanks again :)

**Comment by smhg** [comment]
No problem. Thanks for following up on this! Happy you found out about it.
